site_name: bBpiano

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate

nav:
  - README: bBpiano.md
  - From PDE to PCM: index.md

markdown_extensions:
  - toc:
      toc_depth: 2-4
      permalink: true

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_generic_format

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
